# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hyun Jung KANG"
email: 'clinguist.hjkang@gmail.com'
description: "I'm a Computational Linguistics and Natural Language Processing specialist currently working on my side project WanderWords. \n"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://clinguist-hjkang.github.io" # the base hostname & protocol for your site, e.g. https://example.com
# twitter_username: 'jamigibbs'
linkedin_username: 'clinguist-hjkang'
github_username: 'clinguist-hjkang'
# medium_username: 'blog.jamigibbs.com'

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
remote_theme: jamigibbs/phantom
plugins:
  - jekyll-remote-theme

### Phantom settings
footer_text: '© 2023 Hyun Jung KANG'
admin_name: 'Hyun Jung KANG'
# google_analytics: "UA-9999999-99" # Update with your own tracking ID
enable_contact: true

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
  - { url: '/cv', text: 'CV' }
